# <span style="color:#0b486b">SIT 112 - Data Science Concepts</span>

---
Lecturer: Truyen Tran | truyen.tran@deakin.edu.au<br />

School of Information Technology, <br />
Deakin University, VIC 3216, Australia.

---

## <span style="color:#0b486b">Practical Session 2.2</span>

**The purpose of this session** is to revise more advanced features of Python language, including loops and function declarations, and allow you the time to practice.

**Instructions**
1. After you download this notebook, save it as another copy and rename it to "[yourstudentID]\_prac2_sol.ipynb"
2. As we walk through the notebook, you will be required to write your own code in the cells provided for you. Enter your own code in these cells.

---
### <span style="color:#0b486b">1. Loops</span>

In Python, loops can be programmed in a number of different ways. The most common is the `'for'` loop, which is used together with iterable objects like lists.

#### <span style="color:#0b486b">1.1 For loops</span>

The `for` loop has the ability to iterate over the items of any sequence, such as a list or a string, and repeat executing a statement or a group of statements

In [ ]:
list1 = [1, 2, 3, 4, 5]
for item in list1:   # iterate over the items of the list
    print(item)  # do something 

In [ ]:
# range(n) is a list of n elements [0, 1,..., n-1]
for x in range(4): # by default range start at 0
    # At each step, the statement or a group of statements is executed
    print(x)
    print(x**2)

In [ ]:
course = ["an", "introduction", "to", "data", "science"]
for word in course:
    print(word)

In [ ]:
# use enumerate to access a list items and their indices

course = ["an", "introduction", "to", "data", "science"]
for idx, x in enumerate(course):
    print(idx, x)

**Exercise**: Declare a variable named `my_var` and assign an integer to it. Print all even numbers that are smaller `my_var`

In [ ]:
# your code here
my_var = 10
for i in range(my_var):
    if i % 2 == 0:
        print(i)

#### <span style="color:#0b486b">1.2 List comprehension</span>
A convenient and compact way to initialize lists:

In [ ]:
# range(m, n) is a list: [m, m+1,...,n-1]
list2 = [x**2 for x in range(2, 6)]

print(list2)

**Exercise:** Create a list and fill it with integers from 1 to 50. Now iterate over items of the list and if the item is divisible by 3 and not divisible by 2, print it on the screen.

In [ ]:
# your code here
list50 = []
for i in range(1, 51):
    list50.append(i)

for i in list50:
    if i % 3 == 0 and i % 2 == 1:
        print(i)

**Exercise:** Create a list of integers and print the sum of all elements.

In [ ]:
# your code here
total = 0
for i in list50:
    total += i
print(total)

#### <span style="color:#0b486b">1.3 While loops</span>

While loops repeat a statement or group of statements while a given condition is **True**. It tests the condition before executing the loop body.

In [ ]:
i = 0

while i < 5: # First, the loop test if the condition "i < 5" is True. 
    # end=' ' means that a space will be printed 
    # ...after each number i instead of a line break
    print(i, end=' ')
    
    i += 1
    
print("done")

Note that the `print("done")` statement is a not part of the `while` loop body because of the difference in indentation.

**Exercise:** Define an integer variable named `limit`. Print the largest square number that is smaller than `limit`. For example, if `limit` is 40 then print `36`.

In [ ]:
# your code here
limit = 40
x = 1

while x*x < limit:
    x += 1
print((x-1)**2)

#### <span style="color:#0b486b">1.4 Nested loops</span>

In Python, a loop can appear inside another loop. Execute the cell below:

In [ ]:
sentence = ['Welcome', 'to', 'SIT112']
for word in sentence:
    for character in word:
        print(character, end=' ')
    print()

---
### <span style="color:#0b486b">2. Functions</span>

A function in Python is defined using the keyword `def`, followed by a function name, one or several arguments within parentheses `()`, and a colon `:`. The following code, **with one additional level of indentation**, is the function body. It is recommended to use "docstring" for your functions.

In [ ]:
def func1(s):
    """
    THIS BIT IS CALLED DOCSTRING
    s is the paramter of the function
    Print a string 's' and tell how many characters it has    
    """
    
    print(s + " has " + str(len(s)) + " characters")

In [ ]:
func1("test")

A function can have multiple arguments. For example, the function computes the sum of two numbers:

In [ ]:
def sum_of_2_numbers(a, b):
    """
    This function reads 2 numbers a and b and print their sum
    """
    print(a + b)

Use the ``return`` keyword for functions that return a value. A function can also return multiple values using tuples.

In [ ]:
def powers(x):
    """
    Return a few powers of x.
    """
    return x**2, x**3, x**4

In [ ]:
print(powers(3))

x1, x2, x3 = powers(3)
print(x2)

**Exercise:** 

1. Write a function that takes a list of numbers and prints elements of it that are divisible by 3 and not divisible by 2.
3. Create a a list and fill it with integers from 1 to 50. Use the function you have written in the previous step to print out items of the list that are divisible by 3 and not divisible by 2.

In [ ]:
# your code here
def divByThree(numList):
    for i in numList:
        if i % 3 == 0 and i % 2 == 1:
            print(i)
            
list50 = []
for i in range(1, 51):
    list50.append(i)
    
divByThree(list50)

**Exercise:** Write a function named `largest_square` that takes a variable `limit` and prints the largest square number that smaller than `limit`.

In [ ]:
# your code here
def largest_square(limit):
    x = 1
    while x*x < limit:
        x = x+1
    print((x-1)**2)
        


################
# Then run this cell to see if your function is correct
largest_square(35)
largest_square(70)

#### <span style="color:#0b486b">2.1 Default Argument Values</span>

Python allows a function to have a default value for one or more arguments. This creates a function that can be called with fewer arguments than it is defined to allow. For example:

In [ ]:
def weather(is_sunny, complain='How bad it is!'):
    if not is_sunny:
        print(complain)
        
weather(False)
weather(False, 'I miss the sun!')

You might notice that in section [While loops](#1.3-While-loops), the `print` function has an argument `end=' '` while `print` in other examples does not. It is because `end` is an argument with '\n' (this string indicates a line break) as the default value. That means that the `print` function always prints a line break except when another string is passed. Execute the cell below and see what happend.

In [ ]:
print('A', 'B', 'C', end='_')
print('a', 'b', 'c')

# print function has another argument called 'sep', 
# ...which is used to seperate the printed items. 
# The default value of 'sep' is a space.
print('A', 'B', 'C', sep='_', end=' ')
print('a', 'b', 'c', sep='')

#### <span style="color:#0b486b">2.2 Python build-in functions</span>

The Python interpreter has a number of functions built into it. That means these functions are already defined and you can use them just like your defined functions. In the example above, function len(s) reads a string s and returns the length of s. The function str(n) returns the number n in the string type.

In [ ]:
# the sum function returns the sum of a list
print(sum([1, 2, 3]))

# the abs function returns the absolute value of a number
print(abs(-3.2))

**Exercise:** See more built-in functions in [Python built-in function](https://docs.python.org/2/library/functions.html) and write function named `min_max` that reads a list of numbers and returns the maximun and the minimum number in the list. 

In [ ]:
# your code here
def min_max(l1):
    return(max(l1), min(l1))
    

##############
# Then run this cell to see if your function is correct
print(min_max([3, 2, 4, 1, 10, -5]))
print(min_max([3.5, 2.7, -1.3, 6, -5.2]))

#### <span style="color:#0b486b">2.3 Anonymous functions</span>

Anonymous functions are defined by the keyword `'lambda'` in Python. Functions `'f'` and `'g'` in the cell below basically do the same thing but `'g'` is an anonymous function.

In [ ]:
def f(x):
    return x**2

g = lambda x: x**2

print(f(8), g(8))

Note how we used anonymous functions in the cell below to create the parametric function 'n_increment()'. Now We create new functions by passing 'n' to 'n_incremenet()'. For example 'f5' and 'f9' are functions that add 5 and 9 to their inputs respectively.

In [ ]:
def n_increment(n): 
    return lambda x: x+n

f5 = n_increment(5)
f9 = n_increment(9)

print(f5(2), f9(2))

### <span style="color:#0b486b">3.More on Complex Data Structures</span>

#### <span style="color:#0b486b">3.1 Matrix as nested lists</span>

A matrix of size 3x4 can be implemented by a list of 3 lists of length 4. Execute the cell below:

In [ ]:
matrix = [[0, 1, 2, 3, 4],
          [5, 6, 7, 8, 9],
          [10, 11, 12, 13, 14]]

print(matrix)

# Remember that python indices from 0
print('Element at row 1, column 2:', matrix[1][2])

The `matrix` in the example above can be created by the following way:

In [14]:
matrix = [[row * 4 + column for column in range(4)] for row in range(5)]
print(matrix)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15], [16, 17, 18, 19]]


**Exercise:** 
1. Write a function named `matrix_sum` that takes a matrix as an input and returns the sum of all elements in the matrix. 
2. Declare a matrix A of size 3x3 with arbitrary values and print the `matrix_sum` of A.

In [52]:
# Your code here
import numpy as np
matrix = [[row * 3 + column for column in range(3)] for row in range(3)]
result = sum([sum(item) for item in matrix])
print("For loop Matrix")
print("---------------")
print(matrix)
print()
print("Sum of matrix is :" + str(result))
print()
print("Numpy Matrix")
print("------------")
a = np.matrix('0 1 2; 3 4 5; 6 7 8')
print(a)
print()
print("Sum of matrix is: " + str(a.sum()))

For loop Matrix
---------------
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

Sum of matrix is :36

Numpy Matrix
------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Sum of matrix is: 36


#### <span style="color:#0b486b">3.2 Built-in methods</span>

Python includes a number of methods for complex structures such as strings, lists and dictionaries. Execute these cells below:

In [ ]:
# Split method for string
str1 = 'I-love data science'
space_split = str1.split() 
hyphen_split = str1.split('-')
print('Space splitting:', space_split)
print('Hyphen splitting:', hyphen_split)
# More on split method: https://docs.python.org/3/library/stdtypes.html#str.split

# Check if a string is a list of digits
print('123:', '123'.isdigit())
print('1a3:', '1a3'.isdigit())
print('1.2:', '1.2'.isdigit())

In [ ]:
list3 = [1, 2, 3]

# append an element to list
list3.append(4)
print(list3)

list3.append('I love data science')
print(list3)

# insert an element at an index
list3.insert(3, 'this is an insertion')
print(list3)

In [ ]:
price_dictionary = {'bananas': 2,
                    'kiwis': 5,
                    'apples': 4,
                    'cherries': 15}

# the method returns the keywords in the dictionary
print(price_dictionary.keys())

# the method returns the values in the dictionary
print(price_dictionary.values())

### <span style="color:#0b486b">4. Further reading</span>

[Python functions](https://docs.python.org/3.5/tutorial/controlflow.html#defining-functions) More about python functions on the official Python tutorial website.